<% def aws_driver
@text = <<EOT
---
driver:
  name: aws

platforms:
- name: debian-7.1.0
  run_list:
  - recipe[apt]

provisioner:
  name: chef_zero

suites:
- name: default
  attributes:
    loggly:
      token:
        from_databag: false
        value: ENV['LOGGLY_TOKEN']
  run_list:
    - recipe[loggly_rsyslog_ng_test::default]
EOT
end %>

<% def vagrant_driver
@text = <<EOT
---
driver_plugin: vagrant

platforms:
- name:  debian-7.4
  driver:
    provider: virtualbox
    customize:
      memory: 1024
  run_list:
  - recipe[apt]

provisioner:
  name: chef_zero

suites:
- name: default
  attributes:
    loggly:
      token:
        from_databag: false
        value: ENV['LOGGLY_TOKEN']
  run_list:
    - recipe[loggly_rsyslog_ng_test::default]
EOT
end %>

<%
case ENV['TEST_KITCHEN_DRIVER']
  when 'aws'
    puts 'Using AWS test-kitchen driver'
    _erbout << aws_driver
  when 'vagrant'
    puts 'Using Vagrant test-kitchen driver'
    _erbout << vagrant_driver
  else
    puts "Unknown test-kitchen driver \'#{ENV['TEST_KITCHEN_DRIVER']}\', using Vagrant test-kitchen driver"
    _erbout << vagrant_driver
end
%>
